/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    customers: Customer;
    conversations: Conversation;
    applications: Application;
    'loan-accounts': LoanAccount;
    'write-off-requests': WriteOffRequest;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    customers: CustomersSelect<false> | CustomersSelect<true>;
    conversations: ConversationsSelect<false> | ConversationsSelect<true>;
    applications: ApplicationsSelect<false> | ApplicationsSelect<true>;
    'loan-accounts': LoanAccountsSelect<false> | LoanAccountsSelect<true>;
    'write-off-requests': WriteOffRequestsSelect<false> | WriteOffRequestsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  role: 'admin' | 'supervisor' | 'operations' | 'readonly';
  firstName: string;
  lastName: string;
  avatar?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers".
 */
export interface Customer {
  id: string;
  customerId: string;
  /**
   * Mr, Mrs, Ms, Dr, etc.
   */
  title?: string | null;
  /**
   * Name customer prefers to be called
   */
  preferredName?: string | null;
  firstName?: string | null;
  middleName?: string | null;
  lastName?: string | null;
  /**
   * Full name set by event processor
   */
  fullName?: string | null;
  emailAddress?: string | null;
  mobilePhoneNumber?: string | null;
  dateOfBirth?: string | null;
  /**
   * Set true on customer.verified.v1 event
   */
  identityVerified?: boolean | null;
  /**
   * From SDK: residential_address
   */
  residentialAddress?: {
    /**
     * From SDK: street_number
     */
    streetNumber?: string | null;
    /**
     * From SDK: street_name
     */
    streetName?: string | null;
    /**
     * From SDK: street_type
     */
    streetType?: string | null;
    /**
     * From SDK: unit_number
     */
    unitNumber?: string | null;
    /**
     * Computed full street address
     */
    street?: string | null;
    /**
     * From SDK: suburb
     */
    suburb?: string | null;
    /**
     * Same as suburb (for backward compatibility)
     */
    city?: string | null;
    state?: string | null;
    postcode?: string | null;
    country?: string | null;
    /**
     * From SDK: full_address
     */
    fullAddress?: string | null;
  };
  /**
   * Address for mail delivery (e.g., cards)
   */
  mailingAddress?: {
    street?: string | null;
    city?: string | null;
    state?: string | null;
    postcode?: string | null;
    country?: string | null;
  };
  /**
   * Indicates if customer is a staff member
   */
  staffFlag?: boolean | null;
  /**
   * Indicates if customer is an investor
   */
  investorFlag?: boolean | null;
  /**
   * Indicates if customer is a founder
   */
  founderFlag?: boolean | null;
  /**
   * Indicates if customer requires additional care and support
   */
  vulnerableFlag?: boolean | null;
  /**
   * eKYC identifier from Frankie
   */
  ekycEntityId?: string | null;
  /**
   * Status of eKYC attempt
   */
  ekycStatus?: ('successful' | 'failed' | 'pending') | null;
  /**
   * Lifecycle status of the individual
   */
  individualStatus?: ('LIVING' | 'DECEASED' | 'MISSING') | null;
  identityDocuments?:
    | {
        documentType: 'DRIVERS_LICENCE' | 'PASSPORT' | 'MEDICARE';
        /**
         * e.g., Medicare Card Colour
         */
        documentSubtype?: string | null;
        documentNumber: string;
        expiryDate?: string | null;
        stateOfIssue?: string | null;
        countryOfIssue?: string | null;
        /**
         * Additional document information as key-value pairs
         */
        additionalInfo?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  applications?: (string | Application)[] | null;
  conversations?: (string | Conversation)[] | null;
  /**
   * Loan accounts associated with this customer
   */
  loanAccounts?: (string | LoanAccount)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "applications".
 */
export interface Application {
  id: string;
  applicationNumber: string;
  customerId: string | Customer;
  loanPurpose?: string | null;
  loanAmount?: number | null;
  /**
   * Calculated at 5% of loan amount
   */
  loanFee?: number | null;
  /**
   * Loan amount + fee
   */
  loanTotalPayable?: number | null;
  /**
   * Loan term in days/months
   */
  loanTerm?: number | null;
  customerAttestationAcceptance?: boolean | null;
  statementCaptureConsentProvided?: boolean | null;
  statementCaptureCompleted?: boolean | null;
  productOfferAcceptance?: boolean | null;
  applicationOutcome?: ('pending' | 'approved' | 'declined' | 'withdrawn') | null;
  applicationProcess?: {
    /**
     * Current stage in the application process
     */
    currentProcessStage?: string | null;
    /**
     * Current step within the stage
     */
    currentProcessStep?: string | null;
    startedAt?: string | null;
    updatedAt?: string | null;
    applicationProcessState?:
      | {
          stageName: string;
          complete?: boolean | null;
          prompt?: string | null;
          steps?:
            | {
                stepName: string;
                description?: string | null;
                complete?: boolean | null;
                type?: ('llm' | 'business_logic' | 'user_input') | null;
                completionEventName?: string | null;
                /**
                 * Frontend input type hint
                 */
                answerInputType?: string | null;
                prompts?: {
                  main?: string | null;
                  completenessCheck?: string | null;
                  confirmation?: string | null;
                  outputJson?: string | null;
                  mappingOut?:
                    | {
                        [k: string]: unknown;
                      }
                    | unknown[]
                    | string
                    | number
                    | boolean
                    | null;
                };
                businessLogic?: {
                  moduleName?: string | null;
                  methodName?: string | null;
                  mappingIn?:
                    | {
                        [k: string]: unknown;
                      }
                    | unknown[]
                    | string
                    | number
                    | boolean
                    | null;
                  mappingOut?:
                    | {
                        [k: string]: unknown;
                      }
                    | unknown[]
                    | string
                    | number
                    | boolean
                    | null;
                };
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
    conversation?:
      | {
          role?: ('user' | 'assistant' | 'system') | null;
          content?: string | null;
          timestamp?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Risk and serviceability assessments
   */
  assessments?: {
    /**
     * Identity risk assessment results
     */
    identityRisk?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    /**
     * Serviceability assessment results
     */
    serviceability?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    /**
     * Fraud check results
     */
    fraudCheck?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  /**
   * Agent notes and updates
   */
  noticeboard?:
    | {
        agentName: string;
        content: string;
        timestamp: string;
        versions?:
          | {
              content?: string | null;
              timestamp?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  conversations?: (string | Conversation)[] | null;
  version?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "conversations".
 */
export interface Conversation {
  id: string;
  conversationId: string;
  applicationNumber: string;
  /**
   * Linked customer (may be null if customer not yet created)
   */
  customerId?: (string | null) | Customer;
  /**
   * Customer ID string for queries when relationship not yet established
   */
  customerIdString?: string | null;
  /**
   * Linked application (may be null)
   */
  applicationId?: (string | null) | Application;
  status?: ('active' | 'paused' | 'soft_end' | 'hard_end' | 'approved' | 'declined') | null;
  startedAt: string;
  updatedAt: string;
  utterances?:
    | {
        /**
         * Usually "customer" or "assistant"
         */
        username?: string | null;
        utterance: string;
        /**
         * Internal reasoning for assistant responses
         */
        rationale?: string | null;
        createdAt: string;
        updatedAt?: string | null;
        /**
         * Frontend input type hint (e.g. address, email)
         */
        answerInputType?: string | null;
        /**
         * Previous sequence number in conversation
         */
        prevSeq?: number | null;
        endConversation?: boolean | null;
        /**
         * Additional data for frontend enrichment
         */
        additionalData?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Conversation purpose from summary
   */
  purpose?: string | null;
  /**
   * Key facts from conversation summary
   */
  facts?:
    | {
        fact?: string | null;
        id?: string | null;
      }[]
    | null;
  version?: number | null;
  /**
   * Timestamp of most recent utterance
   */
  lastUtteranceTime?: string | null;
  /**
   * Final decision outcome (APPROVED, DECLINED, REFERRED)
   */
  finalDecision?: string | null;
  /**
   * Risk and serviceability assessments
   */
  assessments?: {
    /**
     * Identity risk assessment data
     */
    identityRisk?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    /**
     * Serviceability assessment data
     */
    serviceability?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    /**
     * Fraud check assessment data
     */
    fraudCheck?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  /**
   * Agent noticeboard posts
   */
  noticeboard?:
    | {
        agentName?: string | null;
        topic?: string | null;
        content?: string | null;
        timestamp?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Additional application data from events
   */
  applicationData?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  createdAt: string;
}
/**
 * Loan accounts projected from ledger events
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "loan-accounts".
 */
export interface LoanAccount {
  id: string;
  /**
   * Unique identifier from ledger service (account_id)
   */
  loanAccountId: string;
  /**
   * Human-readable account number
   */
  accountNumber: string;
  customerId?: (string | null) | Customer;
  /**
   * Customer ID string for queries
   */
  customerIdString?: string | null;
  /**
   * Denormalized for list view performance
   */
  customerName?: string | null;
  /**
   * Original loan terms at disbursement
   */
  loanTerms?: {
    /**
     * Original loan amount (from SDK: loan_amount)
     */
    loanAmount?: number | null;
    /**
     * Fee amount (from SDK: loan_fee)
     */
    loanFee?: number | null;
    /**
     * Total amount to be repaid (from SDK: loan_total_payable)
     */
    totalPayable?: number | null;
    /**
     * Account opening date (from SDK: opened_date)
     */
    openedDate?: string | null;
  };
  /**
   * Current account balances (updated from events)
   */
  balances?: {
    /**
     * Current outstanding balance (from SDK: current_balance)
     */
    currentBalance?: number | null;
    /**
     * Total amount currently owed
     */
    totalOutstanding?: number | null;
    /**
     * Total amount paid to date
     */
    totalPaid?: number | null;
  };
  /**
   * Most recent payment details
   */
  lastPayment?: {
    /**
     * From SDK: last_payment_date
     */
    date?: string | null;
    /**
     * From SDK: last_payment_amount
     */
    amount?: number | null;
  };
  /**
   * Mapped from SDK AccountStatus enum
   */
  accountStatus: 'active' | 'paid_off' | 'in_arrears' | 'written_off';
  /**
   * Original status from SDK (PENDING, ACTIVE, SUSPENDED, CLOSED)
   */
  sdkStatus?: string | null;
  /**
   * Repayment schedule from account.schedule.created.v1
   */
  repaymentSchedule?: {
    /**
     * Unique schedule identifier
     */
    scheduleId?: string | null;
    /**
     * Total number of scheduled payments (from SDK: n_payments)
     */
    numberOfPayments?: number | null;
    /**
     * Payment frequency
     */
    paymentFrequency?: ('weekly' | 'fortnightly' | 'monthly') | null;
    /**
     * Individual scheduled payments
     */
    payments?:
      | {
          /**
           * Payment sequence number (1, 2, 3...)
           */
          paymentNumber: number;
          dueDate: string;
          /**
           * Scheduled payment amount
           */
          amount: number;
          status?: ('scheduled' | 'paid' | 'missed' | 'partial') | null;
          /**
           * Amount actually paid (from schedule.updated)
           */
          amountPaid?: number | null;
          /**
           * Amount still owed on this payment
           */
          amountRemaining?: number | null;
          /**
           * Date payment was completed
           */
          paidDate?: string | null;
          /**
           * Transaction IDs linked to this payment
           */
          linkedTransactionIds?:
            | {
                [k: string]: unknown;
              }
            | unknown[]
            | string
            | number
            | boolean
            | null;
          /**
           * Last time this payment was updated
           */
          lastUpdated?: string | null;
          id?: string | null;
        }[]
      | null;
    /**
     * Schedule creation date
     */
    createdDate?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Write-off requests requiring approval
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "write-off-requests".
 */
export interface WriteOffRequest {
  id: string;
  /**
   * Event correlation ID (conv field). Groups related events in a workflow.
   */
  requestId?: string | null;
  /**
   * Event ID for polling lookup (cause field). Used by client to find projection after command.
   */
  eventId?: string | null;
  /**
   * Human-readable request reference number (e.g., WO-20241211...). Auto-generated if not provided.
   */
  requestNumber?: string | null;
  /**
   * The loan account ID for the write-off request
   */
  loanAccountId: string;
  /**
   * The customer ID associated with the loan account
   */
  customerId: string;
  /**
   * Customer name for display purposes
   */
  customerName?: string | null;
  /**
   * Account number for display purposes
   */
  accountNumber?: string | null;
  /**
   * Write-off amount in AUD
   */
  amount: number;
  /**
   * Account balance at time of request
   */
  originalBalance?: number | null;
  /**
   * Primary reason for the write-off request
   */
  reason:
    | 'hardship'
    | 'bankruptcy'
    | 'deceased'
    | 'unable_to_locate'
    | 'fraud_victim'
    | 'disputed'
    | 'aged_debt'
    | 'other';
  /**
   * Supporting notes and context for the request
   */
  notes?: string | null;
  /**
   * Uploaded supporting documents
   */
  supportingDocuments?:
    | {
        document?: (string | null) | Media;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Current status of the write-off request
   */
  status: 'pending' | 'approved' | 'rejected' | 'cancelled';
  /**
   * Priority level for approval queue
   */
  priority?: ('normal' | 'high' | 'urgent') | null;
  /**
   * Flag for requests exceeding threshold ($10,000)
   */
  requiresSeniorApproval?: boolean | null;
  /**
   * User who submitted the request
   */
  requestedBy?: (string | null) | User;
  /**
   * Requestor name for audit purposes
   */
  requestedByName?: string | null;
  approvalDetails?: {
    decidedBy?: (string | null) | User;
    decidedByName?: string | null;
    decidedAt?: string | null;
    /**
     * Approval or rejection comment
     */
    comment?: string | null;
    /**
     * User ID who approved (from event)
     */
    approvedBy?: string | null;
    approvedByName?: string | null;
    approvedAt?: string | null;
    /**
     * User ID who rejected (from event)
     */
    rejectedBy?: string | null;
    rejectedByName?: string | null;
    rejectedAt?: string | null;
    /**
     * Rejection reason (from event)
     */
    reason?: string | null;
  };
  cancellationDetails?: {
    /**
     * User ID who cancelled (from event)
     */
    cancelledBy?: string | null;
    cancelledByName?: string | null;
    cancelledAt?: string | null;
  };
  /**
   * Timestamp when request was submitted
   */
  requestedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'customers';
        value: string | Customer;
      } | null)
    | ({
        relationTo: 'conversations';
        value: string | Conversation;
      } | null)
    | ({
        relationTo: 'applications';
        value: string | Application;
      } | null)
    | ({
        relationTo: 'loan-accounts';
        value: string | LoanAccount;
      } | null)
    | ({
        relationTo: 'write-off-requests';
        value: string | WriteOffRequest;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  firstName?: T;
  lastName?: T;
  avatar?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers_select".
 */
export interface CustomersSelect<T extends boolean = true> {
  customerId?: T;
  title?: T;
  preferredName?: T;
  firstName?: T;
  middleName?: T;
  lastName?: T;
  fullName?: T;
  emailAddress?: T;
  mobilePhoneNumber?: T;
  dateOfBirth?: T;
  identityVerified?: T;
  residentialAddress?:
    | T
    | {
        streetNumber?: T;
        streetName?: T;
        streetType?: T;
        unitNumber?: T;
        street?: T;
        suburb?: T;
        city?: T;
        state?: T;
        postcode?: T;
        country?: T;
        fullAddress?: T;
      };
  mailingAddress?:
    | T
    | {
        street?: T;
        city?: T;
        state?: T;
        postcode?: T;
        country?: T;
      };
  staffFlag?: T;
  investorFlag?: T;
  founderFlag?: T;
  vulnerableFlag?: T;
  ekycEntityId?: T;
  ekycStatus?: T;
  individualStatus?: T;
  identityDocuments?:
    | T
    | {
        documentType?: T;
        documentSubtype?: T;
        documentNumber?: T;
        expiryDate?: T;
        stateOfIssue?: T;
        countryOfIssue?: T;
        additionalInfo?: T;
        id?: T;
      };
  applications?: T;
  conversations?: T;
  loanAccounts?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "conversations_select".
 */
export interface ConversationsSelect<T extends boolean = true> {
  conversationId?: T;
  applicationNumber?: T;
  customerId?: T;
  customerIdString?: T;
  applicationId?: T;
  status?: T;
  startedAt?: T;
  updatedAt?: T;
  utterances?:
    | T
    | {
        username?: T;
        utterance?: T;
        rationale?: T;
        createdAt?: T;
        updatedAt?: T;
        answerInputType?: T;
        prevSeq?: T;
        endConversation?: T;
        additionalData?: T;
        id?: T;
      };
  purpose?: T;
  facts?:
    | T
    | {
        fact?: T;
        id?: T;
      };
  version?: T;
  lastUtteranceTime?: T;
  finalDecision?: T;
  assessments?:
    | T
    | {
        identityRisk?: T;
        serviceability?: T;
        fraudCheck?: T;
      };
  noticeboard?:
    | T
    | {
        agentName?: T;
        topic?: T;
        content?: T;
        timestamp?: T;
        id?: T;
      };
  applicationData?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "applications_select".
 */
export interface ApplicationsSelect<T extends boolean = true> {
  applicationNumber?: T;
  customerId?: T;
  loanPurpose?: T;
  loanAmount?: T;
  loanFee?: T;
  loanTotalPayable?: T;
  loanTerm?: T;
  customerAttestationAcceptance?: T;
  statementCaptureConsentProvided?: T;
  statementCaptureCompleted?: T;
  productOfferAcceptance?: T;
  applicationOutcome?: T;
  applicationProcess?:
    | T
    | {
        currentProcessStage?: T;
        currentProcessStep?: T;
        startedAt?: T;
        updatedAt?: T;
        applicationProcessState?:
          | T
          | {
              stageName?: T;
              complete?: T;
              prompt?: T;
              steps?:
                | T
                | {
                    stepName?: T;
                    description?: T;
                    complete?: T;
                    type?: T;
                    completionEventName?: T;
                    answerInputType?: T;
                    prompts?:
                      | T
                      | {
                          main?: T;
                          completenessCheck?: T;
                          confirmation?: T;
                          outputJson?: T;
                          mappingOut?: T;
                        };
                    businessLogic?:
                      | T
                      | {
                          moduleName?: T;
                          methodName?: T;
                          mappingIn?: T;
                          mappingOut?: T;
                        };
                    id?: T;
                  };
              id?: T;
            };
        conversation?:
          | T
          | {
              role?: T;
              content?: T;
              timestamp?: T;
              id?: T;
            };
      };
  assessments?:
    | T
    | {
        identityRisk?: T;
        serviceability?: T;
        fraudCheck?: T;
      };
  noticeboard?:
    | T
    | {
        agentName?: T;
        content?: T;
        timestamp?: T;
        versions?:
          | T
          | {
              content?: T;
              timestamp?: T;
              id?: T;
            };
        id?: T;
      };
  conversations?: T;
  version?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "loan-accounts_select".
 */
export interface LoanAccountsSelect<T extends boolean = true> {
  loanAccountId?: T;
  accountNumber?: T;
  customerId?: T;
  customerIdString?: T;
  customerName?: T;
  loanTerms?:
    | T
    | {
        loanAmount?: T;
        loanFee?: T;
        totalPayable?: T;
        openedDate?: T;
      };
  balances?:
    | T
    | {
        currentBalance?: T;
        totalOutstanding?: T;
        totalPaid?: T;
      };
  lastPayment?:
    | T
    | {
        date?: T;
        amount?: T;
      };
  accountStatus?: T;
  sdkStatus?: T;
  repaymentSchedule?:
    | T
    | {
        scheduleId?: T;
        numberOfPayments?: T;
        paymentFrequency?: T;
        payments?:
          | T
          | {
              paymentNumber?: T;
              dueDate?: T;
              amount?: T;
              status?: T;
              amountPaid?: T;
              amountRemaining?: T;
              paidDate?: T;
              linkedTransactionIds?: T;
              lastUpdated?: T;
              id?: T;
            };
        createdDate?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "write-off-requests_select".
 */
export interface WriteOffRequestsSelect<T extends boolean = true> {
  requestId?: T;
  eventId?: T;
  requestNumber?: T;
  loanAccountId?: T;
  customerId?: T;
  customerName?: T;
  accountNumber?: T;
  amount?: T;
  originalBalance?: T;
  reason?: T;
  notes?: T;
  supportingDocuments?:
    | T
    | {
        document?: T;
        description?: T;
        id?: T;
      };
  status?: T;
  priority?: T;
  requiresSeniorApproval?: T;
  requestedBy?: T;
  requestedByName?: T;
  approvalDetails?:
    | T
    | {
        decidedBy?: T;
        decidedByName?: T;
        decidedAt?: T;
        comment?: T;
        approvedBy?: T;
        approvedByName?: T;
        approvedAt?: T;
        rejectedBy?: T;
        rejectedByName?: T;
        rejectedAt?: T;
        reason?: T;
      };
  cancellationDetails?:
    | T
    | {
        cancelledBy?: T;
        cancelledByName?: T;
        cancelledAt?: T;
      };
  requestedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}